"""empty message

Revision ID: afe4c10dacde
Revises: 48c1c4d01fc5
Create Date: 2021-05-24 13:05:41.464354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afe4c10dacde'
down_revision = '48c1c4d01fc5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('order_price', sa.Integer(), nullable=False),
    sa.Column('order_volume', sa.Integer(), nullable=False),
    sa.Column('order_type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['Stocks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_price'),
    sa.UniqueConstraint('order_volume'),
    sa.UniqueConstraint('stock_id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Transactions')
    # ### end Alembic commands ###
