"""empty message

Revision ID: 08d3c031ab00
Revises: 402c2f7812ca
Create Date: 2021-05-24 13:06:42.942320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08d3c031ab00'
down_revision = '402c2f7812ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watchlist_id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['Stocks.id'], ),
    sa.ForeignKeyConstraint(['watchlist_id'], ['Watchlists.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Lists')
    # ### end Alembic commands ###
