"""empty message

Revision ID: e432c0d48642
Revises: ffdc0a98111c
Create Date: 2021-05-24 10:58:38.179434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e432c0d48642'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('cash_balance', sa.Integer(), nullable=True),
    sa.Column('total_investment', sa.Integer(), nullable=True),
    sa.Column('portfolio_stats', sa.ARRAY(sa.Integer()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_unique_constraint(None, 'users', ['first_name'])
    op.create_unique_constraint(None, 'users', ['last_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_table('Portfolios')
    # ### end Alembic commands ###
