"""empty message

Revision ID: 9cb54e27a236
Revises: 08d3c031ab00
Create Date: 2021-05-25 16:41:41.987915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cb54e27a236'
down_revision = '08d3c031ab00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Watchlists_user_id_key', 'Watchlists', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('Watchlists_user_id_key', 'Watchlists', ['user_id'])
    # ### end Alembic commands ###
