"""empty message

Revision ID: 319c334317e4
Revises: d6f8dcbc3d6d
Create Date: 2021-05-27 12:37:21.674338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '319c334317e4'
down_revision = 'd6f8dcbc3d6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Transactions', sa.Column('time_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Transactions', 'time_created')
    # ### end Alembic commands ###
