"""empty message

Revision ID: 6af4fe2d1f83
Revises: 9cb54e27a236
Create Date: 2021-05-25 16:44:59.588636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6af4fe2d1f83'
down_revision = '9cb54e27a236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_first_name_key', 'users', type_='unique')
    op.drop_constraint('users_last_name_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_last_name_key', 'users', ['last_name'])
    op.create_unique_constraint('users_first_name_key', 'users', ['first_name'])
    # ### end Alembic commands ###
